# Generated by Django 5.0.6 on 2024-07-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOS_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('learning_outcomes', models.TextField()),
                ('teaching_hours', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('items', models.IntegerField()),
                ('remembering', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('applying', models.IntegerField()),
                ('analyzing', models.IntegerField()),
                ('evaluating', models.IntegerField()),
                ('creating', models.IntegerField()),
                ('total', models.IntegerField()),
                ('placement', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tos_content',
            },
        ),
    ]
