# Generated by Django 5.0.6 on 2024-07-17 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tos_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tos_content',
            name='teacher_tos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tos_content',
            name='tos_date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
