# Generated by Django 5.0.6 on 2024-07-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tos_content_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tos_content',
            table='tos_content',
        ),
    ]
