# Generated by Django 5.0.6 on 2024-07-17 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tos_delete_tos_contents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TOS',
            new_name='TOS_Content',
        ),
        migrations.AlterModelTable(
            name='tos_content',
            table='tos_content',
        ),
    ]
