# Generated by Django 5.0.6 on 2024-07-18 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tos_tos_content_alter_tos_content_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tos_content',
            old_name='teaching_hours',
            new_name='teachingHours',
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='teacher_tos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tos', to=settings.AUTH_USER_MODEL),
        ),
    ]
