# Generated by Django 5.0.6 on 2024-07-23 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tos_content_totalitems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TOS_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Semester', models.TextField()),
                ('AlumniYear', models.TextField()),
                ('Campus', models.TextField()),
                ('CourseCode', models.TextField()),
                ('Department', models.TextField()),
                ('ExaminationType', models.TextField()),
                ('CourseType', models.TextField()),
                ('ExaminationDate', models.TextField()),
                ('Faculty', models.TextField()),
                ('Chairperson', models.TextField()),
                ('Dean', models.TextField()),
                ('Director', models.TextField()),
                ('tos_info_date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('teacher_tos_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tos_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tos_info',
            },
        ),
    ]
