# Generated by Django 5.0.6 on 2024-07-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tos_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tos_content',
            name='teacher_tos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_tos', to='api.tos_info'),
        ),
    ]
