# Generated by Django 5.0.6 on 2024-08-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_answers_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.TextField(null=True),
        ),
    ]
