# Generated by Django 5.0.6 on 2024-08-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_testpart_questions_test_part_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_instruction',
        ),
    ]
