# Generated by Django 5.0.6 on 2024-08-20 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_exam_exam_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='api.questions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='test_part_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_part_id', to='api.testpart'),
        ),
    ]
