# Generated by Django 5.0.6 on 2024-08-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_answers_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='api.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='test_part_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_part_id', to='api.testpart'),
        ),
    ]
