# Generated by Django 5.0.6 on 2024-08-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_answers_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tos_info',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Admin_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('tos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_info_approval', to='api.tos_info')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
