# Generated by Django 5.0.6 on 2024-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_admin_comment_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tos_info',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Saved'), (1, 'Submitted'), (2, 'Approved'), (3, 'Needs Revision')], default=0, null=True),
        ),
    ]
