# Generated by Django 5.0.6 on 2024-08-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tos_info_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('tos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_info_notif_admin', to='api.tos_info')),
            ],
            options={
                'db_table': 'notification_admin',
            },
        ),
        migrations.CreateModel(
            name='Teacher_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_text', models.TextField()),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('tos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_info_notif_teacher', to='api.tos_info')),
            ],
            options={
                'db_table': 'notification_teacher',
            },
        ),
    ]
