# Generated by Django 5.0.6 on 2024-09-07 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_tos_info_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('taxonomy_level', models.TextField()),
                ('test_type', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_context', to='api.questions')),
            ],
            options={
                'db_table': 'context',
            },
        ),
    ]
