# Generated by Django 5.0.6 on 2024-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
