# Generated by Django 5.0.6 on 2024-09-21 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_tos_content_study_guide_fileupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='file',
            new_name='study_guide',
        ),
        migrations.AlterModelTable(
            name='fileupload',
            table='study_guides',
        ),
    ]
