# Generated by Django 5.0.6 on 2024-09-21 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_tos_conent_fileupload_tos_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='tos_content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tos_content'),
        ),
    ]
