# Generated by Django 5.0.6 on 2024-09-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_fileupload_tos_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='tos_content',
        ),
    ]
