# Generated by Django 5.0.6 on 2024-09-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_fileupload_tos_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='tos_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_content_file', to='api.tos_content'),
        ),
    ]
