# Generated by Django 5.0.6 on 2024-11-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_logs_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='academic_year',
            field=models.TextField(default='2023-2024'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='chairperson',
            field=models.TextField(default='Department Chairperson'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='dean',
            field=models.TextField(default='College Dean'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='director',
            field=models.TextField(default='Campus Executive Director'),
        ),
    ]
