# Generated by Django 5.0.6 on 2024-11-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_settings_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='academic_year',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='chairperson',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='dean',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='director',
            field=models.TextField(),
        ),
    ]
