# Generated by Django 5.0.6 on 2024-11-16 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_settings_academic_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remembering', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('applying', models.IntegerField()),
                ('analyzing', models.IntegerField()),
                ('evaluating', models.IntegerField()),
                ('creating', models.IntegerField()),
                ('tos_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tos_content_id', to='api.tos_content')),
            ],
            options={
                'db_table': 'taxonomy_levels',
            },
        ),
    ]
