# Generated by Django 5.0.6 on 2024-11-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_taxonomylevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='context',
            field=models.TextField(null=True),
        ),
    ]
