# Generated by Django 5.0.6 on 2024-12-11 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_teacher_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_syllabus',
            field=models.FileField(null=True, upload_to='syllabus/'),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='allocation',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='analyzing',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='applying',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='creating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='evaluating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='learning_outcomes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='placement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='remembering',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='teachingHours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tos_content',
            name='understanding',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Learning_Outcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_outcomes', models.TextField()),
                ('teachingHours', models.IntegerField()),
                ('allocation', models.IntegerField()),
                ('items', models.IntegerField()),
                ('remembering', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('applying', models.IntegerField()),
                ('analyzing', models.IntegerField()),
                ('evaluating', models.IntegerField()),
                ('creating', models.IntegerField()),
                ('total', models.IntegerField()),
                ('placement', models.CharField(max_length=100)),
                ('totalItems', models.IntegerField(null=True)),
                ('tos_content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tos_content_lo', to='api.tos_content')),
            ],
            options={
                'db_table': 'learning_outcomes',
            },
        ),
    ]
