# Generated by Django 5.0.6 on 2024-12-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_courses_course_syllabus_alter_tos_content_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_syllabus',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/'),
        ),
    ]
