# Generated by Django 5.0.6 on 2024-12-12 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_courses_course_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learning_outcomes',
            name='totalItems',
        ),
    ]
